name: CMake

on:
  repository_dispatch:
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            TARGET: x86_64-unknown-linux-musl
            COMPILER: gcc
            LINKER: gcc
          - os: ubuntu-latest
            TARGET: armv7-unknown-linux-musleabihf
            COMPILER: arm-linux-gnueabihf-gcc-5
            LINKER: gcc-5-arm-linux-gnueabihf
          - os: windows-latest
            COMPILER: cl
            LINKER: cl

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE
      
    - if: runner.os != 'Windows'
      name: Generate gcovr report
      run: |
        ls -l x64 || ls -l win32
      shell: bash
      
    - name: infomation
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: |
        df -hT
        echo "ref:${{ github.ref }} ls ./"
        cp supernode n2n_${{ matrix.os }}_superonde
        cp edge n2n_${{ matrix.os }}edge
        ls -l

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        files: |
          n2n_${{ matrix.os }}_superonde
          n2n_${{ matrix.os }}edge
