
name: Code lint

on:
  push:
  pull_request:

jobs:
  linting:
    name: Run test environment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install essential
        run: |
          sudo apt-get update
          sudo apt-get install build-essential

      - name: generate a makefile and use it to install more packages
        run: |
          ./autogen.sh
          ./configure
          make build-dep

      - name: Run the styleguide lint
        run: |
          make lint
