---
name: OpenWrt Build

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Test ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: arc_archs
            target: archs38-generic
            runtime_test: false

          - arch: arm_cortex-a9_vfpv3-d16
            target: mvebu-cortexa9
            runtime_test: false

          - arch: mips_24kc
            target: ath79-generic
            runtime_test: false

          - arch: mipsel_24kc
            target: mt7621
            runtime_test: false

          - arch: powerpc_464fp
            target: apm821xx-nand
            runtime_test: false

          - arch: powerpc_8540
            target: mpc85xx-p1010
            runtime_test: false

          - arch: aarch64_cortex-a53
            target: mvebu-cortexa53
            runtime_test: true

          - arch: arm_cortex-a15_neon-vfpv4
            target: armvirt-32
            runtime_test: true

          - arch: i386_pentium-mmx
            target: x86-geode
            runtime_test: true

          - arch: x86_64
            target: x86-64
            runtime_test: true

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build
        uses: openwrt/gh-action-sdk@v5
        env:
          ARCH: ${{ matrix.arch }}
          FEEDNAME: n2n_ci
          PACKAGES: openwrt

      - name: Move created packages to project dir
        run: |
          mkdir -p ipk-${{ matrix.arch }}
          cp bin/packages/${{ matrix.arch }}/n2n_ci/*.ipk ipk-${{ matrix.arch }} || true

      - name: Store packages
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: ipk-${{ matrix.arch }}/

      - name: Rename logs
        run: sudo mv -f logs logs-${{ matrix.arch }}

      - name: Store logs
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: logs-${{ matrix.arch }}/

      - name: Remove logs
        run: sudo rm -rf logs-${{ matrix.arch }}/ || true

      - name: Register QEMU
        if: ${{ matrix.runtime_test }}
        run: sudo docker run --rm --privileged aptman/qus -s -- -p

      - name: Build Docker container
        if: ${{ matrix.runtime_test }}
        run: |
          git checkout HEAD .github/openwrt
          docker build -t test-container --build-arg ARCH .github/openwrt/
        env:
          ARCH: ${{ matrix.arch }}

      - name: Test via Docker container
        if: ${{ matrix.runtime_test }}
        run: docker run --rm -v $GITHUB_WORKSPACE:/ci test-container
