---
name: OpenWrt Build

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Test ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: arc_archs
            target: archs38-generic

          - arch: arm_cortex-a9_vfpv3-d16
            target: mvebu-cortexa9

          - arch: mips_24kc
            target: ath79-generic

          - arch: mipsel_24kc
            target: mt7621

          - arch: powerpc_464fp
            target: apm821xx-nand

          - arch: powerpc_8540
            target: mpc85xx-p1010

          - arch: aarch64_cortex-a53
            target: mvebu-cortexa53

          - arch: arm_cortex-a15_neon-vfpv4
            target: armvirt-32

          - arch: i386_pentium-mmx
            target: x86-geode

          - arch: x86_64
            target: x86-64

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build
        uses: openwrt/gh-action-sdk@v5
        env:
          ARCH: ${{ matrix.arch }}
          FEEDNAME: n2n_ci
          PACKAGES: openwrt

      - name: Move created packages to project dir
        run: |
          mkdir -p ipk-${{ matrix.arch }}
          cp bin/packages/${{ matrix.arch }}/n2n_ci/*.ipk ipk-${{ matrix.arch }} || true

      - name: Store packages
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: ipk-${{ matrix.arch }}/

      - name: Rename logs
        run: sudo mv -f logs logs-${{ matrix.arch }}

      - name: Store logs
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: logs-${{ matrix.arch }}/

      - name: Remove logs
        run: sudo rm -rf logs-${{ matrix.arch }}/ || true
