---
name: Openwrt Build

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:

jobs:
  build:
    name: Run test environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout openwrt
        uses: actions/checkout@v2
        with:
          repository: openwrt/openwrt

      - name: Set openwrt ref
        id: ref
        run: echo ::set-output name=OPENWRT::$(git rev-parse --short HEAD)

      - name: Cache openwrt source downloads
        uses: actions/cache@v2
        with:
          path: dl
          key: openwrt-dl-${{ steps.ref.outputs.OPENWRT }}

      - name: Setup openwrt config and environment
        run: |
          echo "CONFIG_TARGET_x86=y" >.config
          echo "CONFIG_TARGET_x86_64=y" >>.config
          make defconfig

      - name: Download openwrt sources
        run: |
          make download

      - name: Build openwrt build environment
        run: |
          make -j3 tools/install toolchain/install

      - name: Build n2n dependancies
        run: |
          make package/libs/libpcap/compile

      - name: Checkout n2n
        uses: actions/checkout@v2
        with:
          path: n2n

      - name: Add n2n package
        run: |
          cp -r n2n/packages/openwrt package/n2n
          echo "CONFIG_PACKAGE_n2n-edge=m" >>.config
          echo "CONFIG_PACKAGE_n2n-supernode=m" >>.config
          make defconfig

      - name: Build n2n openwrt packages
        run: |
          make package/n2n/compile V=s

# FIXME: add a way to run the test suite!
#      - name: Run embedded tests
#        run: make test

      - name: Upload built artifacts
        uses: actions/upload-artifact@v2
        with:
          name: built-ipkgs
          path: bin/packages/*/base/*.ipk
